name: Weekly Model Retraining
on:
This runs at 03:00 UTC every Monday
schedule:
- cron: '0 3 * * 1'
This allows you to run the workflow manually from the Actions tab
workflow_dispatch:
jobs:
train-models:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v3
  - name: Set up Python 3.9
    uses: actions/setup-python@v4
    with:
      python-version: 3.9

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install pandas requests scikit-learn skl2onnx

  - name: Run model training script
    run: python train_models_automated.py

  - name: Commit and push new models
    run: |
      git config --global user.name 'github-actions[bot]'
      git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      git add models/
      if git diff-index --quiet HEAD; then
        echo "No model changes to commit."
      else
        git commit -m "Automated weekly model retraining"
        git push
      fi

