name: Weekly Model Retraining

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  train-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install pandas requests scikit-learn skl2onnx packaging

      - name: Run Python training script
        run: python train_models_automated.py

      - name: Commit and push new models
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          # Force add all files in the models directory
          git add -f models/
          # Check the status to see what has been staged
          git status
          # Commit only if there are changes to commit
          git diff --staged --quiet || git commit -m "Automated weekly model retraining"
          # Force push the changes
          git push
