name: Weekly Model Retraining
Controls when the action will run.
This runs "at 03:00 on Monday" (UTC time).
on:
schedule:
- cron: '0 3 * * 1'
Allows you to run this workflow manually from the Actions tab
workflow_dispatch:
jobs:
train-models:
runs-on: ubuntu-latest
steps:
  # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - name: Checkout repository
    uses: actions/checkout@v3

  # 2. Sets up Python environment
  - name: Set up Python 3.9
    uses: actions/setup-python@v4
    with:
      python-version: 3.9

  # 3. Installs the necessary Python libraries
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install pandas requests scikit-learn skl2onnx

  # 4. Runs the training script to generate the .onnx files
  - name: Run model training script
    run: python train_models_automated.py

  # 5. Commits the newly trained model files back to the repository
  - name: Commit and push new models
    run: |
      git config --global user.name 'github-actions[bot]'
      git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      git add models/
      # Check if there are any changes to commit
      if git diff-index --quiet HEAD; then
        echo "No model changes to commit."
      else
        git commit -m "Automated weekly model retraining"
        git push
      fi

