name: Weekly Model Retraining
on:
schedule:
- cron: '0 3 * * 1'
workflow_dispatch:
jobs:
train-models:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: 3.9

  - name: Install dependencies
    run: pip install pandas requests scikit-learn skl2onnx

  - name: Run model training script
    run: python train_models_automated.py

  - name: Commit and push new models
    run: |
      git config user.name 'github-actions[bot]'
      git config user.email 'github-actions[bot]@users.noreply.github.com'
      git add models/ -f
      git commit -m "Automated weekly model retraining" || echo "No changes to commit"
      git push || echo "No changes to push"

